### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by msadowski** [bsaund/rviz_voxelgrid_visuals#4]
Hi!

Thanks for doing an interesting project and making it visible to the world! I'm just about to do a deep dive and check it out. 

I noticed that the current project does not specify the license. Are you planning to add it at any point in the future? I think if your project does not specify the licence it is is as "All rights reserved" - no one should use it in their projects. Thanks!

**Comment by bsaund** [comment]
I added a license.
https://github.com/bsaund/rviz_voxelgrid_visuals/pull/5

My intent is to remove any legal or licensing barriers for someone interested in using this package.


Let me know how you end up using this project!

**Comment by msadowski** [comment]
That was quick, thanks!! One more tip: you can declare the same licence in both package.xml file - if you ever release the package to ROS distro it will most likely automatically show the licence on the ROS wiki.
